server:
  port: 80

#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblogservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root