#端口号
server:
  port: 8080
#spring的配置
spring:
  application:
    name: myblogservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myblogservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    dbcp2:
      max-idle: 10 #连接池最大的空闲连接数量
      max-wait-millis: 10000 #连接池等待连接返回的最大等待时间，毫秒单位
      min-idle: 5 #指定必须保持连接的最小值
      initial-size: 5 #启动连接池时，初始建立的连接数量
#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #配置日志
  mapper-locations: classpath:/mapper/*Mapper.xml  #配置mapper.xml地址包

